-- user = {
--    accountUuid: ...
--    userUuid: ...
--    login: ...
--    name: ...
-- }
INSERT INTO ${schema~}.users(acct_id, user_uuid, login, name)
  VALUES ((SELECT id
             FROM ${schema~}.accounts
            WHERE acct_uuid = ${accountUuid}),
          ${userUuid}, ${login}, ${name})
